# -*- coding: utf-8 -*-
"""Image Processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yC5yIuNcjedtVUjZYVPYwYC6D9eG3Qbn
"""

import base64
import time

start_time = time.time()
# Read the image file
with open("img04.jpeg", "rb") as image_file:
    # Encode the image in Base64 format
    base64_image = base64.b64encode(image_file.read())

# Save the Base64 encoded data to a text file
with open("image_base64_04.txt", "w") as text_file:
    text_file.write(base64_image.decode("utf-8"))

end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.2f} seconds")

# prompt: Now turn above text files into actual images

import base64
import time

# Read the base64 encoded data from the text file
with open("decrypted_00.txt", "r") as text_file:
    base64_image = text_file.read()

# Decode the Base64 encoded data into bytes
image_bytes = base64.b64decode(base64_image)

# Save the decoded bytes to a new image file
with open("decoded_image_00.jpeg", "wb") as image_file:
    image_file.write(image_bytes)

